import React from "react";

export const sections = [
    {
        id: 1,
        ref : 0,
        title: 'Clássicos',
        data: [{
            id: '1',
            title: 'Burguer Bacon',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        },
        {
            id: '2',
            title: 'Burguer Cheddar',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        },
        {
            id: '3',
            title: 'Double Rio',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 17,00',
            pricePrevious: 'R$ 21,00',
        },
        {
            id: '4',
            title: 'Rio Burguer',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        },]
    },
    {
        id: 2,
        ref : 0,
        title: 'Pão de alho',
        data: [{
            id: '5',
            title: 'Haja coração',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        },
        {
            id: '6',
            title: 'Pão de alho c/ camarão',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        },
        {
            id: '7',
            title: 'Picanha nobre',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        }]
    },
    {
        id: 3,
        ref : 0,
        title: 'Artesanal',
        data: [{
            id: '9',
            title: 'Burguer-Alho',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        },
        {
            id: '10',
            title: 'Cheddar Bacon',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        },
        {
            id: '11',
            title: 'Fire Melt',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        },
        {
            id: '12',
            title: 'Onion Crispy',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        }]
    },
    {
        id: 4,
        ref : 0,
        title: 'Premium Burger',
        data: [{
            id: '13',
            title: 'Fire Burger',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        },
        {
            id: '14',
            title: 'Parma',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        },
        {
            id: '15',
            title: 'Picanha Top Premium',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        },
        {
            id: '16',
            title: 'Special Cheddar',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        }]
    },
    {
        id: 5,
        ref : 0,
        title: 'Chicken Honey',
        data: [{
            id: '17',
            title: 'Honey Bacon Cheese',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        },
        {
            id: '18',
            title: 'Rio Master Chicken',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            image: 'https://source.unsplash.com/900x900/?food,hamburger',
            price: 'R$ 11,00',
            pricePrevious: 'R$ 18,00',
        }]
    },
]
